#!/bin/bash

cd ../../../spl/

./spl ../Programs/module27/task2/haltprog.spl
./spl ../Programs/module27/task2/int_console.spl
./spl ../Programs/module27/task2/int_disk.spl
./spl ../Programs/module27/task2/int_timer.spl
./spl ../Programs/module27/task2/int_exhandler.spl
./spl ../Programs/module27/task2/module_boot.spl
./spl ../Programs/module27/task2/module_process.spl
./spl ../Programs/module27/task2/module_memory.spl
./spl ../Programs/module27/task2/module_file.spl
./spl ../Programs/module27/task2/module_device.spl
./spl ../Programs/module27/task2/module_resource.spl
./spl ../Programs/module27/task2/module_pager.spl
./spl ../Programs/module27/task2/module_scheduler.spl
./spl ../Programs/module27/task2/os_startup.spl
./spl ../Programs/module27/task2/syscall_exit.spl
./spl ../Programs/module27/task2/syscall_print.spl
./spl ../Programs/module27/task2/syscall_read.spl
./spl ../Programs/module27/task2/syscall_exec.spl
./spl ../Programs/module27/task2/syscall_fork.spl
./spl ../Programs/module27/task2/syscall_shutdown.spl
./spl ../Programs/module27/task2/syscall_login.spl
./spl ../Programs/module27/task2/syscall_logout.spl
./spl ../Programs/module27/task2/syscall_4.spl
./spl ../Programs/module27/task2/syscall_5.spl
./spl ../Programs/module27/task2/syscall_11.spl
./spl ../Programs/module27/task2/syscall_13.spl
./spl ../Programs/module27/task2/syscall_14.spl
./spl ../Programs/module27/task2/syscall_16.spl

echo "==================SPL Compilation done==================="



cd ../expl/

./expl ../Programs/module27/task2/idle.expl
mv assemblycode.xsm ../Programs/module27/task2/idle.xsm
./expl ../Programs/module27/task2/login.expl
mv assemblycode.xsm ../Programs/module27/task2/login.xsm
./expl ../Programs/module27/task2/shell.expl
mv assemblycode.xsm ../Programs/module27/task2/shell.xsm
./expl ../Programs/module27/task2/ls.expl
mv assemblycode.xsm ../Programs/module27/task2/ls.xsm
./expl ../Programs/module27/task2/rm.expl
mv assemblycode.xsm ../Programs/module27/task2/rm.xsm
./expl ../Programs/module27/task2/cp.expl
mv assemblycode.xsm ../Programs/module27/task2/cp.xsm
./expl ../Programs/module27/task2/cat.expl
mv assemblycode.xsm ../Programs/module27/task2/cat.xsm
./expl ../Programs/module27/task2/ru.expl
mv assemblycode.xsm ../Programs/module27/task2/ru.xsm
./expl ../Programs/module27/task2/lu.expl
mv assemblycode.xsm ../Programs/module27/task2/lu.xsm
./expl ../Programs/module27/task2/fork.expl
mv assemblycode.xsm ../Programs/module27/task2/fork.xsm
./expl ../Programs/module27/task2/pid.expl
mv assemblycode.xsm ../Programs/module27/task2/pid.xsm

echo "==================EXPL Compilation done=================="



cd ../xfs-interface/

./xfs-interface fdisk
./xfs-interface load --os ../Programs/module27/task2/os_startup.xsm
./xfs-interface load --init ../Programs/module27/task2/login.xsm
./xfs-interface load --idle ../Programs/module27/task2/idle.xsm
./xfs-interface load --shell ../Programs/module27/task2/shell.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --exhandler ../Programs/module27/task2/int_exhandler.xsm
./xfs-interface load --int=timer ../Programs/module27/task2/int_timer.xsm
./xfs-interface load --int=disk ../Programs/module27/task2/int_disk.xsm
./xfs-interface load --int=console ../Programs/module27/task2/int_console.xsm
./xfs-interface load --int=4 ../Programs/module27/task2/syscall_4.xsm
./xfs-interface load --int=5 ../Programs/module27/task2/syscall_5.xsm
./xfs-interface load --int=6 ../Programs/module27/task2/syscall_read.xsm
./xfs-interface load --int=7 ../Programs/module27/task2/syscall_print.xsm
./xfs-interface load --int=8 ../Programs/module27/task2/syscall_fork.xsm
./xfs-interface load --int=9 ../Programs/module27/task2/syscall_exec.xsm
./xfs-interface load --int=10 ../Programs/module27/task2/syscall_exit.xsm
./xfs-interface load --int=11 ../Programs/module27/task2/syscall_11.xsm
./xfs-interface load --int=12 ../Programs/module27/task2/syscall_logout.xsm
./xfs-interface load --int=13 ../Programs/module27/task2/syscall_13.xsm
./xfs-interface load --int=14 ../Programs/module27/task2/syscall_14.xsm
./xfs-interface load --int=15 ../Programs/module27/task2/syscall_shutdown.xsm
./xfs-interface load --int=16 ../Programs/module27/task2/syscall_16.xsm
./xfs-interface load --int=17 ../Programs/module27/task2/syscall_login.xsm
./xfs-interface load --module 0 ../Programs/module27/task2/module_resource.xsm
./xfs-interface load --module 1 ../Programs/module27/task2/module_process.xsm
./xfs-interface load --module 2 ../Programs/module27/task2/module_memory.xsm
./xfs-interface load --module 3 ../Programs/module27/task2/module_file.xsm
./xfs-interface load --module 4 ../Programs/module27/task2/module_device.xsm
./xfs-interface load --module 5 ../Programs/module27/task2/module_scheduler.xsm
./xfs-interface load --module 6 ../Programs/module27/task2/module_pager.xsm
./xfs-interface load --module 7 ../Programs/module27/task2/module_boot.xsm
./xfs-interface load --exec ../Programs/module27/task2/ls.xsm
./xfs-interface load --exec ../Programs/module27/task2/rm.xsm
./xfs-interface load --exec ../Programs/module27/task2/cp.xsm
./xfs-interface load --exec ../Programs/module27/task2/cat.xsm
./xfs-interface load --exec ../Programs/module27/task2/lu.xsm
./xfs-interface load --exec ../Programs/module27/task2/ru.xsm
./xfs-interface load --exec ../Programs/module27/task2/fork.xsm
./xfs-interface load --exec ../Programs/module27/task2/pid.xsm

echo "======================Files loaded======================="


cd ../xsm/

if [ "$1" = "debug" ]; then
    ./xsm --debug --timer 1024
else
    ./xsm --timer 1024
fi

cd ../xfs-interface/
./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/module27/task2/inodeusertable.txt
./xfs-interface dump --rootfile
mv rootfile.txt ../Programs/module27/task2/rootfile.txt

cd ../Programs/module27/task2/
