#!/bin/bash
./xfs-interface load --int=10 ../Programs/module14/task2/int10.xsm
./xfs-interface load --exhandler ../Programs/module14/task2/haltprog.xsm
./xfs-interface load --int=timer ../Programs/module14/task2/timer.xsm
./xfs-interface load --os ../Programs/module14/task2/os_startup.xsm
./xfs-interface load --init ../Programs/module14/task2/init.xsm
./xfs-interface load --int=7 ../Programs/module14/task2/print.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --idle ../Programs/module14/task2/idle.xsm
./xfs-interface load --module 7 ../Programs/module14/task2/boot.xsm
./xfs-interface load --module 5 ../Programs/module14/task2/scheduler.xsm
./xfs-interface load --exec ../Programs/module14/task2/even.xsm
./xfs-interface load --exec ../Programs/module14/task2/primes.xsm
./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/module14/task2/inodeusertable.txt
