#!/bin/bash

cd ../../../spl/

./spl ../Programs/module23/task2/haltprog.spl
./spl ../Programs/module23/task2/int_console.spl
./spl ../Programs/module23/task2/int_disk.spl
./spl ../Programs/module23/task2/int_timer.spl
./spl ../Programs/module23/task2/int_exhandler.spl
./spl ../Programs/module23/task2/module_boot.spl
./spl ../Programs/module23/task2/module_process.spl
./spl ../Programs/module23/task2/module_memory.spl
./spl ../Programs/module23/task2/module_device.spl
./spl ../Programs/module23/task2/module_resource.spl
./spl ../Programs/module23/task2/module_scheduler.spl
./spl ../Programs/module23/task2/os_startup.spl
./spl ../Programs/module23/task2/syscall_exit.spl
./spl ../Programs/module23/task2/syscall_print.spl
./spl ../Programs/module23/task2/syscall_read.spl
./spl ../Programs/module23/task2/syscall_exec.spl
./spl ../Programs/module23/task2/syscall_fork.spl
./spl ../Programs/module23/task2/syscall_4.spl
./spl ../Programs/module23/task2/syscall_11.spl
./spl ../Programs/module23/task2/syscall_13.spl
./spl ../Programs/module23/task2/syscall_14.spl
./spl ../Programs/module23/task2/syscall_shutdown.spl

echo "==================SPL Compilation done==================="



cd ../expl/

./expl ../Programs/module23/task2/idle.expl
mv assemblycode.xsm ../Programs/module23/task2/idle.xsm
./expl ../Programs/module23/task2/init.expl
mv assemblycode.xsm ../Programs/module23/task2/init.xsm
./expl ../Programs/module23/task2/merge_sort_seq.expl
mv assemblycode.xsm ../Programs/module23/task2/mergeSeq.xsm
./expl ../Programs/module23/task2/merge_sort_con.expl
mv assemblycode.xsm ../Programs/module23/task2/mergeCon.xsm

echo "==================EXPL Compilation done=================="



cd ../xfs-interface/

./xfs-interface fdisk
./xfs-interface load --os ../Programs/module23/task2/os_startup.xsm
./xfs-interface load --init ../Programs/module23/task2/init.xsm
./xfs-interface load --idle ../Programs/module23/task2/idle.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --exhandler ../Programs/module23/task2/int_exhandler.xsm
./xfs-interface load --int=timer ../Programs/module23/task2/int_timer.xsm
./xfs-interface load --int=disk ../Programs/module23/task2/int_disk.xsm
./xfs-interface load --int=console ../Programs/module23/task2/int_console.xsm
./xfs-interface load --int=4 ../Programs/module23/task2/syscall_4.xsm
./xfs-interface load --int=6 ../Programs/module23/task2/syscall_read.xsm
./xfs-interface load --int=7 ../Programs/module23/task2/syscall_print.xsm
./xfs-interface load --int=8 ../Programs/module23/task2/syscall_fork.xsm
./xfs-interface load --int=9 ../Programs/module23/task2/syscall_exec.xsm
./xfs-interface load --int=10 ../Programs/module23/task2/syscall_exit.xsm
./xfs-interface load --int=11 ../Programs/module23/task2/syscall_11.xsm
./xfs-interface load --int=13 ../Programs/module23/task2/syscall_13.xsm
./xfs-interface load --int=14 ../Programs/module23/task2/syscall_14.xsm
./xfs-interface load --int=15 ../Programs/module23/task2/syscall_shutdown.xsm
./xfs-interface load --module 0 ../Programs/module23/task2/module_resource.xsm
./xfs-interface load --module 1 ../Programs/module23/task2/module_process.xsm
./xfs-interface load --module 2 ../Programs/module23/task2/module_memory.xsm
./xfs-interface load --module 4 ../Programs/module23/task2/module_device.xsm
./xfs-interface load --module 5 ../Programs/module23/task2/module_scheduler.xsm
./xfs-interface load --module 7 ../Programs/module23/task2/module_boot.xsm
./xfs-interface load --exec ../Programs/module23/task2/mergeCon.xsm
./xfs-interface load --exec ../Programs/module23/task2/mergeSeq.xsm

echo "======================Files loaded======================="



cd ../xsm/ && ./xsm --timer 1024

cd ../xfs-interface/
./xfs-interface dump --inodeusertable
mv inodeusertable.txt ../Programs/module23/task2/inodeusertable.txt
./xfs-interface dump --rootfile
mv rootfile.txt ../Programs/module23/task2/rootfile.txt

cd ../Programs/module23/task2/
