#!/bin/bash
./spl ../Programs/module18/task1/haltprog.spl
./spl ../Programs/module18/task1/int_console.spl
./spl ../Programs/module18/task1/int_disk.spl
./spl ../Programs/module18/task1/int_timer.spl
./spl ../Programs/module18/task1/module_boot.spl
./spl ../Programs/module18/task1/module_process.spl
./spl ../Programs/module18/task1/module_memory.spl
./spl ../Programs/module18/task1/module_device.spl
./spl ../Programs/module18/task1/module_resource.spl
./spl ../Programs/module18/task1/module_scheduler.spl
./spl ../Programs/module18/task1/os_startup.spl
./spl ../Programs/module18/task1/syscall_exit.spl
./spl ../Programs/module18/task1/syscall_print.spl
./spl ../Programs/module18/task1/syscall_read.spl
./spl ../Programs/module18/task1/syscall_exec.spl
