#!/bin/bash
./spl ../Programs/module16/task2/haltprog.spl
./spl ../Programs/module16/task2/int_console.spl
./spl ../Programs/module16/task2/int_timer.spl
./spl ../Programs/module16/task2/module_boot.spl
./spl ../Programs/module16/task2/module_deviceManager.spl
./spl ../Programs/module16/task2/module_resource.spl
./spl ../Programs/module16/task2/module_scheduler.spl
./spl ../Programs/module16/task2/os_startup.spl
./spl ../Programs/module16/task2/syscall_exit.spl
./spl ../Programs/module16/task2/syscall_print.spl
./spl ../Programs/module16/task2/syscall_read.spl
