#!/bin/bash
./expl ../Programs/module16/task2/idle.expl
mv assemblycode.xsm ../Programs/module16/task2/idle.xsm
./expl ../Programs/module16/task2/init.expl
mv assemblycode.xsm ../Programs/module16/task2/init.xsm
