#!/bin/bash
./spl ../Programs/module13/task1/os_startup.spl
./spl ../Programs/module13/task1/timer.spl
./spl ../Programs/module13/task1/haltprog.spl
./spl ../Programs/module13/task1/print.spl
./spl ../Programs/module13/task1/boot.spl
