#!/bin/bash
./spl ../Programs/module14/task1/os_startup.spl
./spl ../Programs/module14/task1/timer.spl
./spl ../Programs/module14/task1/haltprog.spl
./spl ../Programs/module14/task1/print.spl
./spl ../Programs/module14/task1/boot.spl
./spl ../Programs/module14/task1/int10.spl
./spl ../Programs/module14/task1/scheduler.spl
