#!/bin/bash
./xfs-interface fdisk
./xfs-interface load --os ../Programs/module20/task3/os_startup.xsm
./xfs-interface load --init ../Programs/module20/task3/init.xsm
./xfs-interface load --idle ../Programs/module20/task3/idle.xsm
./xfs-interface load --library ../expl/library.lib
./xfs-interface load --exhandler ../Programs/module20/task3/int_exhandler.xsm
./xfs-interface load --int=timer ../Programs/module20/task3/int_timer.xsm
./xfs-interface load --int=disk ../Programs/module20/task3/int_disk.xsm
./xfs-interface load --int=console ../Programs/module20/task3/int_console.xsm
./xfs-interface load --int=6 ../Programs/module20/task3/syscall_read.xsm
./xfs-interface load --int=7 ../Programs/module20/task3/syscall_print.xsm
./xfs-interface load --int=8 ../Programs/module20/task3/syscall_fork.xsm
./xfs-interface load --int=9 ../Programs/module20/task3/syscall_exec.xsm
./xfs-interface load --int=10 ../Programs/module20/task3/syscall_exit.xsm
./xfs-interface load --module 0 ../Programs/module20/task3/module_resource.xsm
./xfs-interface load --module 1 ../Programs/module20/task3/module_process.xsm
./xfs-interface load --module 2 ../Programs/module20/task3/module_memory.xsm
./xfs-interface load --module 4 ../Programs/module20/task3/module_device.xsm
./xfs-interface load --module 5 ../Programs/module20/task3/module_scheduler.xsm
./xfs-interface load --module 7 ../Programs/module20/task3/module_boot.xsm

