#!/bin/bash
./xfs-interface load --exhandler ../Programs/module9/task2/haltprog.xsm
./xfs-interface load --int=10 ../Programs/module9/task2/haltprog.xsm
./xfs-interface load --int=timer ../Programs/module9/task2/timer.xsm
./xfs-interface load --os ../Programs/module9/task2/os_startup.xsm
./xfs-interface load --init ../Programs/module9/task2/cube.xsm
./xfs-interface load --library ../expl/library.lib

