#!/bin/bash
./expl ../Programs/module20/task1/idle.expl
mv assemblycode.xsm ../Programs/module20/task1/idle.xsm
./expl ../Programs/module20/task1/init.expl
mv assemblycode.xsm ../Programs/module20/task1/init.xsm
./expl ../Programs/module20/task1/linklist.expl
mv assemblycode.xsm ../Programs/module20/task1/linklist.xsm
