#!/bin/bash
./xfs-interface load --exhandler ../Programs/module11/task4/haltprog.xsm
./xfs-interface load --int=10 ../Programs/module11/task4/haltprog.xsm
./xfs-interface load --int=timer ../Programs/module11/task4/timer.xsm
./xfs-interface load --os ../Programs/module11/task4/os_startup.xsm
./xfs-interface load --init ../Programs/module11/task4/numbers.xsm
./xfs-interface load --int=7 ../Programs/module11/task4/print.xsm
./xfs-interface load --library ../Programs/module11/task4/lib.lib
